apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  labels:
    run: {{.Release.Name}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    run: {{.Release.Name}}
